site_name: My First test Docs
pages:
    - Home: index.md
    - About: about.md
    - Git: 
        - 'Cheat sheet': 'Git/gitCommands.md'
        - 'GitFlow': 'Git/gitflow.md'        
theme: readthedocs
