site_name: Fleet git flow
pages:
    - Home: index.md
    - Mkdocs: about.md
    - Fleet:
        - 'Fleet/roadmap.md'
        - 'pointer API':
            - 'Fleet/PointerAPI/TODO.md'
            - 'Fleet/PointerAPI/pointerapi.md'
            - 'Fleet/PointerAPI/ApiMapping.md'
    - Git:         
        - 'What is Git': 'Git/WhatisGit.md'
        - 'GitFlow': 'Git/gitflow.md' 
        - 'Cheat sheet': 'Git/gitCommands.md'       
theme: readthedocs
