site_name: My First test Docs
pages:
    - Home: index.md
    - About: about.md
    - Git:         
        - 'What is Git': 'Git/WhatisGit.md'
        - 'GitFlow': 'Git/gitflow.md' 
        - 'Cheat sheet': 'Git/gitCommands.md'       
theme: readthedocs